# Generated by Django 4.1.7 on 2023-03-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_appointment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lastName',
        ),
    ]
