# Generated by Django 4.1.7 on 2023-03-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_appointment_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='appointment',
            name='lastName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
